### ISSUE TITLE
How to setup a development environment under kodi/xbmc

### ISSUE THREAD

**Issue by hbiyik** [hbiyik/script.module.triblercore#1]
navigate to your addon folder which located in *near* the Userdata folder, with ***"addons"*** name. http://kodi.wiki/view/Userdata

Download necessary packages in this directory. Best practice is to clone them:

git clone https://github.com/hbiyik/script.module.triblercore.git
git clone https://github.com/hbiyik/script.module.abi.git
git clone https://github.com/hbiyik/script.module.cryptography.git
git clone https://github.com/hbiyik/script.module.m2crypto.git
git clone https://github.com/hbiyik/script.module.apsw.git
git clone https://github.com/hbiyik/script.module.idna.git
git clone https://github.com/hbiyik/script.module.netifaces.git
git clone https://github.com/hbiyik/script.module.cffi.git
git clone https://github.com/hbiyik/script.module.incremental.git
git clone https://github.com/hbiyik/script.module.plyvel.git
git clone https://github.com/hbiyik/script.module.libnacl.git
git clone https://github.com/hbiyik/script.module.pycparser.git
git clone https://github.com/hbiyik/script.module.twisted.git
git clone https://github.com/hbiyik/script.module.constantly.git
git clone https://github.com/hbiyik/script.module.libtorrent.git
git clone https://github.com/hbiyik/script.module.pywin32ctypes.git
git clone https://github.com/hbiyik/script.module.zope.interface.git

Since there is no repository at, above modules also require
script.module.six
script.module.requests
script.module.chardet

you can also extract those from offical repozip files located at:
http://ftp.halifax.rwth-aachen.de/xbmc/addons/
accroding to your kodi version (they are pretty generic kodi version should not matter at all)

Then launch kodi, kodi wil automatically find those addons and list them. under settings -> system -> addons -> dependecies.

If you dont see them clear the addon*.db under <Userdata>/Database/addon*.db.

If addons are listed but grayed out it means that theya re disabled, go to tribler core, click on it and select activate. Especially Kodi 17 Krypton does not automatically activate manually installed addons

**Comment by EinNarr** [comment]
https://github.com/hbiyik/script.module.chardet.git is 404. It seems to be a private repo.

**Comment by hbiyik** [comment]
i have forgotten create a repo for it, ill commit when i return home

**Comment by hbiyik** [comment]
@EinNarr  should be fine now

**Comment by hbiyik** [comment]
i have checked again. script.module.chrdet is already in official repo you can downoad from

http://ftp.halifax.rwth-aachen.de/xbmc/addons/jarvis/script.module.chardet/

**Comment by EinNarr** [comment]
I tried that official repo yesterday but forgot to report to you. It worked like magic on Nexus with the newest firmware. The phone is quite hot, as expected. It also happened with the genuine tribler Android client.
It is truly amazing. Would you please send the PR again?
